import { CountryListItem } from "../components/Calendar/types";

export const GC_COUNTRY_CALENDAR_MAP: { [key: string]: string } = {
  Afghanistan: "en.af%23holiday@group.v.calendar.google.com",
  Albania: "en.al%23holiday@group.v.calendar.google.com",
  Algeria: "en.dz%23holiday@group.v.calendar.google.com",
  "American Samoa": "en.as%23holiday@group.v.calendar.google.com",
  Andorra: "en.ad%23holiday@group.v.calendar.google.com",
  Angola: "en.ao%23holiday@group.v.calendar.google.com",
  Anguilla: "en.ai%23holiday@group.v.calendar.google.com",
  "Antigua and Barbuda": "en.ag%23holiday@group.v.calendar.google.com",
  Argentina: "en.ar%23holiday@group.v.calendar.google.com",
  Armenia: "en.am%23holiday@group.v.calendar.google.com",
  Aruba: "en.aw%23holiday@group.v.calendar.google.com",
  Australia: "en.australian%23holiday@group.v.calendar.google.com",
  Austria: "en.austrian%23holiday@group.v.calendar.google.com",
  Azerbaijan: "en.az%23holiday@group.v.calendar.google.com",
  Bahamas: "en.bs%23holiday@group.v.calendar.google.com",
  Bahrain: "en.bh%23holiday@group.v.calendar.google.com",
  Bangladesh: "en.bd%23holiday@group.v.calendar.google.com",
  Barbados: "en.bb%23holiday@group.v.calendar.google.com",
  Belarus: "en.by%23holiday@group.v.calendar.google.com",
  Belgium: "en.be%23holiday@group.v.calendar.google.com",
  Belize: "en.bz%23holiday@group.v.calendar.google.com",
  Benin: "en.bj%23holiday@group.v.calendar.google.com",
  Bermuda: "en.bm%23holiday@group.v.calendar.google.com",
  Bhutan: "en.bt%23holiday@group.v.calendar.google.com",
  Bolivia: "en.bo%23holiday@group.v.calendar.google.com",
  "Bosnia and Herzegovina": "en.ba%23holiday@group.v.calendar.google.com",
  Botswana: "en.bw%23holiday@group.v.calendar.google.com",
  Brazil: "en.brazilian%23holiday@group.v.calendar.google.com",
  "British Virgin Islands": "en.vg%23holiday@group.v.calendar.google.com",
  "Brunei Darussalam": "en.bn%23holiday@group.v.calendar.google.com",
  Bulgaria: "en.bulgarian%23holiday@group.v.calendar.google.com",
  "Burkina Faso": "en.bf%23holiday@group.v.calendar.google.com",
  Burundi: "en.bi%23holiday@group.v.calendar.google.com",
  Cambodia: "en.kh%23holiday@group.v.calendar.google.com",
  Cameroon: "en.cm%23holiday@group.v.calendar.google.com",
  Canada: "en.canadian%23holiday@group.v.calendar.google.com",
  "Cape Verde": "en.cv%23holiday@group.v.calendar.google.com",
  "Cayman Islands": "en.ky%23holiday@group.v.calendar.google.com",
  "Central African Republic": "en.cf%23holiday@group.v.calendar.google.com",
  Chad: "en.td%23holiday@group.v.calendar.google.com",
  Chile: "en.cl%23holiday@group.v.calendar.google.com",
  China: "en.china%23holiday@group.v.calendar.google.com",
  Colombia: "en.co%23holiday@group.v.calendar.google.com",
  "com,oros": "en.km%23holiday@group.v.calendar.google.com",
  Congo: "en.cg%23holiday@group.v.calendar.google.com",
  "Cook Islands": "en.ck%23holiday@group.v.calendar.google.com",
  "Costa Rica": "en.cr%23holiday@group.v.calendar.google.com",
  "Côte d'Ivoire": "en.ci%23holiday@group.v.calendar.google.com",
  Croatia: "en.croatian%23holiday@group.v.calendar.google.com",
  Cuba: "en.cu%23holiday@group.v.calendar.google.com",
  Curaçao: "en.cw%23holiday@group.v.calendar.google.com",
  Cyprus: "en.cy%23holiday@group.v.calendar.google.com",
  Czechia: "en.czech%23holiday@group.v.calendar.google.com",
  "Democratic People's Republic of Korea":
    "en.kp%23holiday@group.v.calendar.google.com",
  Denmark: "en.danish%23holiday@group.v.calendar.google.com",
  Djibouti: "en.dj%23holiday@group.v.calendar.google.com",
  Dominica: "en.dm%23holiday@group.v.calendar.google.com",
  "Dominican Republic": "en.do%23holiday@group.v.calendar.google.com",
  Ecuador: "en.ec%23holiday@group.v.calendar.google.com",
  Egypt: "en.eg%23holiday@group.v.calendar.google.com",
  "El Salvador": "en.sv%23holiday@group.v.calendar.google.com",
  "Equatorial Guinea": "en.gq%23holiday@group.v.calendar.google.com",
  Eritrea: "en.er%23holiday@group.v.calendar.google.com",
  Estonia: "en.ee%23holiday@group.v.calendar.google.com",
  Ethiopia: "en.et%23holiday@group.v.calendar.google.com",
  "Falkland Islands (Malvinas)": "en.fk%23holiday@group.v.calendar.google.com",
  "Faroe Islands": "en.fo%23holiday@group.v.calendar.google.com",
  "Federated States of Micronesia":
    "en.fm%23holiday@group.v.calendar.google.com",
  Fiji: "en.fj%23holiday@group.v.calendar.google.com",
  Finland: "en.finnish%23holiday@group.v.calendar.google.com",
  France: "en.french%23holiday@group.v.calendar.google.com",
  "French Guiana": "en.gf%23holiday@group.v.calendar.google.com",
  "French Polynesia": "en.pf%23holiday@group.v.calendar.google.com",
  Gabon: "en.ga%23holiday@group.v.calendar.google.com",
  Gambia: "en.gm%23holiday@group.v.calendar.google.com",
  Georgia: "en.ge%23holiday@group.v.calendar.google.com",
  Germany: "en.german%23holiday@group.v.calendar.google.com",
  Ghana: "en.gh%23holiday@group.v.calendar.google.com",
  Gibraltar: "en.gi%23holiday@group.v.calendar.google.com",
  Greece: "en.greek%23holiday@group.v.calendar.google.com",
  Greenland: "en.gl%23holiday@group.v.calendar.google.com",
  Grenada: "en.gd%23holiday@group.v.calendar.google.com",
  Guam: "en.gu%23holiday@group.v.calendar.google.com",
  Guatemala: "en.gt%23holiday@group.v.calendar.google.com",
  Guernsey: "en.gg%23holiday@group.v.calendar.google.com",
  Guinea: "en.gn%23holiday@group.v.calendar.google.com",
  "Guinea-Bissau": "en.gw%23holiday@group.v.calendar.google.com",
  Guyana: "en.gy%23holiday@group.v.calendar.google.com",
  Haiti: "en.ht%23holiday@group.v.calendar.google.com",
  "Holy See (Vatican City State)":
    "en.va%23holiday@group.v.calendar.google.com",
  Honduras: "en.hn%23holiday@group.v.calendar.google.com",
  "Hong Kong": "en.hong_kong%23holiday@group.v.calendar.google.com",
  Hungary: "en.hungarian%23holiday@group.v.calendar.google.com",
  Iceland: "en.is%23holiday@group.v.calendar.google.com",
  India: "en.indian%23holiday@group.v.calendar.google.com",
  Indonesia: "en.indonesian%23holiday@group.v.calendar.google.com",
  Iraq: "en.iq%23holiday@group.v.calendar.google.com",
  Ireland: "en.irish%23holiday@group.v.calendar.google.com",
  "Islamic Republic of Iran": "en.ir%23holiday@group.v.calendar.google.com",
  "Isle of Man": "en.im%23holiday@group.v.calendar.google.com",
  Israel: "en.jewish%23holiday@group.v.calendar.google.com",
  Italy: "en.italian%23holiday@group.v.calendar.google.com",
  Jamaica: "en.jm%23holiday@group.v.calendar.google.com",
  Japan: "en.japanese%23holiday@group.v.calendar.google.com",
  Jersey: "en.je%23holiday@group.v.calendar.google.com",
  Jordan: "en.jo%23holiday@group.v.calendar.google.com",
  Kazakhstan: "en.kz%23holiday@group.v.calendar.google.com",
  Kenya: "en.ke%23holiday@group.v.calendar.google.com",
  Kiribati: "en.ki%23holiday@group.v.calendar.google.com",
  Kuwait: "en.kw%23holiday@group.v.calendar.google.com",
  Kyrgyzstan: "en.kg%23holiday@group.v.calendar.google.com",
  "Lao People's Democratic Republic":
    "en.la%23holiday@group.v.calendar.google.com",
  Latvia: "en.latvian%23holiday@group.v.calendar.google.com",
  Lebanon: "en.lb%23holiday@group.v.calendar.google.com",
  Lesotho: "en.ls%23holiday@group.v.calendar.google.com",
  Liberia: "en.lr%23holiday@group.v.calendar.google.com",
  Libya: "en.ly%23holiday@group.v.calendar.google.com",
  Liechtenstein: "en.li%23holiday@group.v.calendar.google.com",
  Lithuania: "en.lithuanian%23holiday@group.v.calendar.google.com",
  Luxembourg: "en.lu%23holiday@group.v.calendar.google.com",
  Macao: "en.mo%23holiday@group.v.calendar.google.com",
  Madagascar: "en.mg%23holiday@group.v.calendar.google.com",
  Malawi: "en.mw%23holiday@group.v.calendar.google.com",
  Malaysia: "en.malaysia%23holiday@group.v.calendar.google.com",
  Maldives: "en.mv%23holiday@group.v.calendar.google.com",
  Mali: "en.ml%23holiday@group.v.calendar.google.com",
  Malta: "en.mt%23holiday@group.v.calendar.google.com",
  "Marshall Islands": "en.mh%23holiday@group.v.calendar.google.com",
  Martinique: "en.mq%23holiday@group.v.calendar.google.com",
  Mauritania: "en.mr%23holiday@group.v.calendar.google.com",
  Mauritius: "en.mu%23holiday@group.v.calendar.google.com",
  Mayotte: "en.yt%23holiday@group.v.calendar.google.com",
  Mexico: "en.mexican%23holiday@group.v.calendar.google.com",
  Moldova: "en.md%23holiday@group.v.calendar.google.com",
  Monaco: "en.mc%23holiday@group.v.calendar.google.com",
  Mongolia: "en.mn%23holiday@group.v.calendar.google.com",
  Montenegro: "en.me%23holiday@group.v.calendar.google.com",
  Montserrat: "en.ms%23holiday@group.v.calendar.google.com",
  Morocco: "en.ma%23holiday@group.v.calendar.google.com",
  Mozambique: "en.mz%23holiday@group.v.calendar.google.com",
  Myanmar: "en.mm%23holiday@group.v.calendar.google.com",
  Namibia: "en.na%23holiday@group.v.calendar.google.com",
  Nauru: "en.nr%23holiday@group.v.calendar.google.com",
  Nepal: "en.np%23holiday@group.v.calendar.google.com",
  Netherlands: "en.dutch%23holiday@group.v.calendar.google.com",
  "New Caledonia": "en.nc%23holiday@group.v.calendar.google.com",
  "New Zealand": "en.new_zealand%23holiday@group.v.calendar.google.com",
  Nicaragua: "en.ni%23holiday@group.v.calendar.google.com",
  Niger: "en.ne%23holiday@group.v.calendar.google.com",
  Nigeria: "en.ng%23holiday@group.v.calendar.google.com",
  "Northern Mariana Islands": "en.mp%23holiday@group.v.calendar.google.com",
  Norway: "en.norwegian%23holiday@group.v.calendar.google.com",
  Oman: "en.om%23holiday@group.v.calendar.google.com",
  Pakistan: "en.pk%23holiday@group.v.calendar.google.com",
  Palau: "en.pw%23holiday@group.v.calendar.google.com",
  Panama: "en.pa%23holiday@group.v.calendar.google.com",
  "Papua New Guinea": "en.pg%23holiday@group.v.calendar.google.com",
  Paraguay: "en.py%23holiday@group.v.calendar.google.com",
  Peru: "en.pe%23holiday@group.v.calendar.google.com",
  Philippines: "en.philippines%23holiday@group.v.calendar.google.com",
  Poland: "en.polish%23holiday@group.v.calendar.google.com",
  Portugal: "en.portuguese%23holiday@group.v.calendar.google.com",
  "Puerto Rico": "en.pr%23holiday@group.v.calendar.google.com",
  Qatar: "en.qa%23holiday@group.v.calendar.google.com",
  "Republic of Korea": "en.south_korea%23holiday@group.v.calendar.google.com",
  Réunion: "en.re%23holiday@group.v.calendar.google.com",
  Romania: "en.romanian%23holiday@group.v.calendar.google.com",
  "Russian Federation": "en.russian%23holiday@group.v.calendar.google.com",
  Rwanda: "en.rw%23holiday@group.v.calendar.google.com",
  "Saint Barthélemy": "en.bl%23holiday@group.v.calendar.google.com",
  "Saint Helena": "en.sh%23holiday@group.v.calendar.google.com",
  "Saint Kitts and Nevis": "en.kn%23holiday@group.v.calendar.google.com",
  "Saint Lucia": "en.lc%23holiday@group.v.calendar.google.com",
  "Saint Martin (French part)": "en.mf%23holiday@group.v.calendar.google.com",
  "Saint Pierre and Miquelon": "en.pm%23holiday@group.v.calendar.google.com",
  "Saint Vincent and the Grenadines":
    "en.vc%23holiday@group.v.calendar.google.com",
  Samoa: "en.ws%23holiday@group.v.calendar.google.com",
  "San Marino": "en.sm%23holiday@group.v.calendar.google.com",
  "Sao Tome and Principe": "en.st%23holiday@group.v.calendar.google.com",
  "Saudi Arabia": "en.saudiarabian%23holiday@group.v.calendar.google.com",
  Senegal: "en.sn%23holiday@group.v.calendar.google.com",
  Serbia: "en.rs%23holiday@group.v.calendar.google.com",
  Seychelles: "en.sc%23holiday@group.v.calendar.google.com",
  "Sierra Leone": "en.sl%23holiday@group.v.calendar.google.com",
  Singapore: "en.singapore%23holiday@group.v.calendar.google.com",
  "Sint Maarten (Dutch part)": "en.sx%23holiday@group.v.calendar.google.com",
  Slovakia: "en.slovak%23holiday@group.v.calendar.google.com",
  Slovenia: "en.slovenian%23holiday@group.v.calendar.google.com",
  "Solomon Islands": "en.sb%23holiday@group.v.calendar.google.com",
  Somalia: "en.so%23holiday@group.v.calendar.google.com",
  "South Africa": "en.sa%23holiday@group.v.calendar.google.com",
  "South Sudan": "en.ss%23holiday@group.v.calendar.google.com",
  Spain: "en.spain%23holiday@group.v.calendar.google.com",
  "Sri Lanka": "en.lk%23holiday@group.v.calendar.google.com",
  Sudan: "en.sd%23holiday@group.v.calendar.google.com",
  Suriname: "en.sr%23holiday@group.v.calendar.google.com",
  Swaziland: "en.sz%23holiday@group.v.calendar.google.com",
  Sweden: "en.swedish%23holiday@group.v.calendar.google.com",
  Switzerland: "en.ch%23holiday@group.v.calendar.google.com",
  "Syrian Arab Republic": "en.sy%23holiday@group.v.calendar.google.com",
  Taiwan: "en.taiwan%23holiday@group.v.calendar.google.com",
  Tajikistan: "en.tj%23holiday@group.v.calendar.google.com",
  Thailand: "en.th%23holiday@group.v.calendar.google.com",
  "The Democratic Republic of the Congo":
    "en.cd%23holiday@group.v.calendar.google.com",
  "The Former Yugoslav Republic of Macedonia":
    "en.mk%23holiday@group.v.calendar.google.com",
  "Timor-Leste": "en.tl%23holiday@group.v.calendar.google.com",
  Togo: "en.tg%23holiday@group.v.calendar.google.com",
  Tonga: "en.to%23holiday@group.v.calendar.google.com",
  "Trinidad and Tobago": "en.tt%23holiday@group.v.calendar.google.com",
  Tunisia: "en.tn%23holiday@group.v.calendar.google.com",
  Turkey: "en.turkish%23holiday@group.v.calendar.google.com",
  Turkmenistan: "en.tm%23holiday@group.v.calendar.google.com",
  "Turks and Caicos Islands": "en.tc%23holiday@group.v.calendar.google.com",
  Tuvalu: "en.tv%23holiday@group.v.calendar.google.com",
  "U.S. Virgin Islands": "en.vi%23holiday@group.v.calendar.google.com",
  Uganda: "en.ug%23holiday@group.v.calendar.google.com",
  Ukraine: "en.ukrainian%23holiday@group.v.calendar.google.com",
  "United Arab Emirates": "en.ae%23holiday@group.v.calendar.google.com",
  "United Kingdom": "en.uk%23holiday@group.v.calendar.google.com",
  "United Republic of Tanzania": "en.tz%23holiday@group.v.calendar.google.com",
  "United States": "en.usa%23holiday@group.v.calendar.google.com",
  Uruguay: "en.uy%23holiday@group.v.calendar.google.com",
  Uzbekistan: "en.uz%23holiday@group.v.calendar.google.com",
  Vanuatu: "en.vu%23holiday@group.v.calendar.google.com",
  Venezuela: "en.ve%23holiday@group.v.calendar.google.com",
  Vietnam: "en.vietnamese%23holiday@group.v.calendar.google.com",
  "Wallis and Futuna": "en.wf%23holiday@group.v.calendar.google.com",
  Yemen: "en.ye%23holiday@group.v.calendar.google.com",
  Zambia: "en.zm%23holiday@group.v.calendar.google.com",
  Zimbabwe: "en.zw%23holiday@group.v.calendar.google.com",
};

export const COUNTRY_LIST: CountryListItem[] = [
  { Code: "AF", Name: "Afghanistan" },
  { Code: "AX", Name: "\u00c5land Islands" },
  { Code: "AL", Name: "Albania" },
  { Code: "DZ", Name: "Algeria" },
  { Code: "AS", Name: "American Samoa" },
  { Code: "AD", Name: "Andorra" },
  { Code: "AO", Name: "Angola" },
  { Code: "AI", Name: "Anguilla" },
  { Code: "AQ", Name: "Antarctica" },
  { Code: "AG", Name: "Antigua and Barbuda" },
  { Code: "AR", Name: "Argentina" },
  { Code: "AM", Name: "Armenia" },
  { Code: "AW", Name: "Aruba" },
  { Code: "AU", Name: "Australia" },
  { Code: "AT", Name: "Austria" },
  { Code: "AZ", Name: "Azerbaijan" },
  { Code: "BS", Name: "Bahamas" },
  { Code: "BH", Name: "Bahrain" },
  { Code: "BD", Name: "Bangladesh" },
  { Code: "BB", Name: "Barbados" },
  { Code: "BY", Name: "Belarus" },
  { Code: "BE", Name: "Belgium" },
  { Code: "BZ", Name: "Belize" },
  { Code: "BJ", Name: "Benin" },
  { Code: "BM", Name: "Bermuda" },
  { Code: "BT", Name: "Bhutan" },
  { Code: "BO", Name: "Bolivia, Plurinational State of" },
  { Code: "BQ", Name: "Bonaire, Sint Eustatius and Saba" },
  { Code: "BA", Name: "Bosnia and Herzegovina" },
  { Code: "BW", Name: "Botswana" },
  { Code: "BV", Name: "Bouvet Island" },
  { Code: "BR", Name: "Brazil" },
  { Code: "IO", Name: "British Indian Ocean Territory" },
  { Code: "BN", Name: "Brunei Darussalam" },
  { Code: "BG", Name: "Bulgaria" },
  { Code: "BF", Name: "Burkina Faso" },
  { Code: "BI", Name: "Burundi" },
  { Code: "KH", Name: "Cambodia" },
  { Code: "CM", Name: "Cameroon" },
  { Code: "CA", Name: "Canada" },
  { Code: "CV", Name: "Cape Verde" },
  { Code: "KY", Name: "Cayman Islands" },
  { Code: "CF", Name: "Central African Republic" },
  { Code: "TD", Name: "Chad" },
  { Code: "CL", Name: "Chile" },
  { Code: "CN", Name: "China" },
  { Code: "CX", Name: "Christmas Island" },
  { Code: "CC", Name: "Cocos (Keeling) Islands" },
  { Code: "CO", Name: "Colombia" },
  { Code: "KM", Name: "Comoros" },
  { Code: "CG", Name: "Congo" },
  { Code: "CD", Name: "Congo, the Democratic Republic of the" },
  { Code: "CK", Name: "Cook Islands" },
  { Code: "CR", Name: "Costa Rica" },
  { Code: "CI", Name: "C\u00f4te d'Ivoire" },
  { Code: "HR", Name: "Croatia" },
  { Code: "CU", Name: "Cuba" },
  { Code: "CW", Name: "Cura\u00e7ao" },
  { Code: "CY", Name: "Cyprus" },
  { Code: "CZ", Name: "Czech Republic" },
  { Code: "DK", Name: "Denmark" },
  { Code: "DJ", Name: "Djibouti" },
  { Code: "DM", Name: "Dominica" },
  { Code: "DO", Name: "Dominican Republic" },
  { Code: "EC", Name: "Ecuador" },
  { Code: "EG", Name: "Egypt" },
  { Code: "SV", Name: "El Salvador" },
  { Code: "GQ", Name: "Equatorial Guinea" },
  { Code: "ER", Name: "Eritrea" },
  { Code: "EE", Name: "Estonia" },
  { Code: "ET", Name: "Ethiopia" },
  { Code: "FK", Name: "Falkland Islands (Malvinas)" },
  { Code: "FO", Name: "Faroe Islands" },
  { Code: "FJ", Name: "Fiji" },
  { Code: "FI", Name: "Finland" },
  { Code: "FR", Name: "France" },
  { Code: "GF", Name: "French Guiana" },
  { Code: "PF", Name: "French Polynesia" },
  { Code: "TF", Name: "French Southern Territories" },
  { Code: "GA", Name: "Gabon" },
  { Code: "GM", Name: "Gambia" },
  { Code: "GE", Name: "Georgia" },
  { Code: "DE", Name: "Germany" },
  { Code: "GH", Name: "Ghana" },
  { Code: "GI", Name: "Gibraltar" },
  { Code: "GR", Name: "Greece" },
  { Code: "GL", Name: "Greenland" },
  { Code: "GD", Name: "Grenada" },
  { Code: "GP", Name: "Guadeloupe" },
  { Code: "GU", Name: "Guam" },
  { Code: "GT", Name: "Guatemala" },
  { Code: "GG", Name: "Guernsey" },
  { Code: "GN", Name: "Guinea" },
  { Code: "GW", Name: "Guinea-Bissau" },
  { Code: "GY", Name: "Guyana" },
  { Code: "HT", Name: "Haiti" },
  { Code: "HM", Name: "Heard Island and McDonald Islands" },
  { Code: "VA", Name: "Holy See (Vatican City State)" },
  { Code: "HN", Name: "Honduras" },
  { Code: "HK", Name: "Hong Kong" },
  { Code: "HU", Name: "Hungary" },
  { Code: "IS", Name: "Iceland" },
  { Code: "IN", Name: "India" },
  { Code: "ID", Name: "Indonesia" },
  { Code: "IR", Name: "Iran, Islamic Republic of" },
  { Code: "IQ", Name: "Iraq" },
  { Code: "IE", Name: "Ireland" },
  { Code: "IM", Name: "Isle of Man" },
  { Code: "IL", Name: "Israel" },
  { Code: "IT", Name: "Italy" },
  { Code: "JM", Name: "Jamaica" },
  { Code: "JP", Name: "Japan" },
  { Code: "JE", Name: "Jersey" },
  { Code: "JO", Name: "Jordan" },
  { Code: "KZ", Name: "Kazakhstan" },
  { Code: "KE", Name: "Kenya" },
  { Code: "KI", Name: "Kiribati" },
  { Code: "KP", Name: "Korea, Democratic People's Republic of" },
  { Code: "KR", Name: "Korea, Republic of" },
  { Code: "KW", Name: "Kuwait" },
  { Code: "KG", Name: "Kyrgyzstan" },
  { Code: "LA", Name: "Lao People's Democratic Republic" },
  { Code: "LV", Name: "Latvia" },
  { Code: "LB", Name: "Lebanon" },
  { Code: "LS", Name: "Lesotho" },
  { Code: "LR", Name: "Liberia" },
  { Code: "LY", Name: "Libya" },
  { Code: "LI", Name: "Liechtenstein" },
  { Code: "LT", Name: "Lithuania" },
  { Code: "LU", Name: "Luxembourg" },
  { Code: "MO", Name: "Macao" },
  { Code: "MK", Name: "Macedonia, the Former Yugoslav Republic of" },
  { Code: "MG", Name: "Madagascar" },
  { Code: "MW", Name: "Malawi" },
  { Code: "MY", Name: "Malaysia" },
  { Code: "MV", Name: "Maldives" },
  { Code: "ML", Name: "Mali" },
  { Code: "MT", Name: "Malta" },
  { Code: "MH", Name: "Marshall Islands" },
  { Code: "MQ", Name: "Martinique" },
  { Code: "MR", Name: "Mauritania" },
  { Code: "MU", Name: "Mauritius" },
  { Code: "YT", Name: "Mayotte" },
  { Code: "MX", Name: "Mexico" },
  { Code: "FM", Name: "Micronesia, Federated States of" },
  { Code: "MD", Name: "Moldova, Republic of" },
  { Code: "MC", Name: "Monaco" },
  { Code: "MN", Name: "Mongolia" },
  { Code: "ME", Name: "Montenegro" },
  { Code: "MS", Name: "Montserrat" },
  { Code: "MA", Name: "Morocco" },
  { Code: "MZ", Name: "Mozambique" },
  { Code: "MM", Name: "Myanmar" },
  { Code: "NA", Name: "Namibia" },
  { Code: "NR", Name: "Nauru" },
  { Code: "NP", Name: "Nepal" },
  { Code: "NL", Name: "Netherlands" },
  { Code: "NC", Name: "New Caledonia" },
  { Code: "NZ", Name: "New Zealand" },
  { Code: "NI", Name: "Nicaragua" },
  { Code: "NE", Name: "Niger" },
  { Code: "NG", Name: "Nigeria" },
  { Code: "NU", Name: "Niue" },
  { Code: "NF", Name: "Norfolk Island" },
  { Code: "MP", Name: "Northern Mariana Islands" },
  { Code: "NO", Name: "Norway" },
  { Code: "OM", Name: "Oman" },
  { Code: "PK", Name: "Pakistan" },
  { Code: "PW", Name: "Palau" },
  { Code: "PS", Name: "Palestine, State of" },
  { Code: "PA", Name: "Panama" },
  { Code: "PG", Name: "Papua New Guinea" },
  { Code: "PY", Name: "Paraguay" },
  { Code: "PE", Name: "Peru" },
  { Code: "PH", Name: "Philippines" },
  { Code: "PN", Name: "Pitcairn" },
  { Code: "PL", Name: "Poland" },
  { Code: "PT", Name: "Portugal" },
  { Code: "PR", Name: "Puerto Rico" },
  { Code: "QA", Name: "Qatar" },
  { Code: "RE", Name: "R\u00e9union" },
  { Code: "RO", Name: "Romania" },
  { Code: "RU", Name: "Russian Federation" },
  { Code: "RW", Name: "Rwanda" },
  { Code: "BL", Name: "Saint Barth\u00e9lemy" },
  { Code: "SH", Name: "Saint Helena, Ascension and Tristan da Cunha" },
  { Code: "KN", Name: "Saint Kitts and Nevis" },
  { Code: "LC", Name: "Saint Lucia" },
  { Code: "MF", Name: "Saint Martin (French part)" },
  { Code: "PM", Name: "Saint Pierre and Miquelon" },
  { Code: "VC", Name: "Saint Vincent and the Grenadines" },
  { Code: "WS", Name: "Samoa" },
  { Code: "SM", Name: "San Marino" },
  { Code: "ST", Name: "Sao Tome and Principe" },
  { Code: "SA", Name: "Saudi Arabia" },
  { Code: "SN", Name: "Senegal" },
  { Code: "RS", Name: "Serbia" },
  { Code: "SC", Name: "Seychelles" },
  { Code: "SL", Name: "Sierra Leone" },
  { Code: "SG", Name: "Singapore" },
  { Code: "SX", Name: "Sint Maarten (Dutch part)" },
  { Code: "SK", Name: "Slovakia" },
  { Code: "SI", Name: "Slovenia" },
  { Code: "SB", Name: "Solomon Islands" },
  { Code: "SO", Name: "Somalia" },
  { Code: "ZA", Name: "South Africa" },
  { Code: "GS", Name: "South Georgia and the South Sandwich Islands" },
  { Code: "SS", Name: "South Sudan" },
  { Code: "ES", Name: "Spain" },
  { Code: "LK", Name: "Sri Lanka" },
  { Code: "SD", Name: "Sudan" },
  { Code: "SR", Name: "Suriname" },
  { Code: "SJ", Name: "Svalbard and Jan Mayen" },
  { Code: "SZ", Name: "Swaziland" },
  { Code: "SE", Name: "Sweden" },
  { Code: "CH", Name: "Switzerland" },
  { Code: "SY", Name: "Syrian Arab Republic" },
  { Code: "TW", Name: "Taiwan, Province of China" },
  { Code: "TJ", Name: "Tajikistan" },
  { Code: "TZ", Name: "Tanzania, United Republic of" },
  { Code: "TH", Name: "Thailand" },
  { Code: "TL", Name: "Timor-Leste" },
  { Code: "TG", Name: "Togo" },
  { Code: "TK", Name: "Tokelau" },
  { Code: "TO", Name: "Tonga" },
  { Code: "TT", Name: "Trinidad and Tobago" },
  { Code: "TN", Name: "Tunisia" },
  { Code: "TR", Name: "Turkey" },
  { Code: "TM", Name: "Turkmenistan" },
  { Code: "TC", Name: "Turks and Caicos Islands" },
  { Code: "TV", Name: "Tuvalu" },
  { Code: "UG", Name: "Uganda" },
  { Code: "UA", Name: "Ukraine" },
  { Code: "AE", Name: "United Arab Emirates" },
  { Code: "GB", Name: "United Kingdom" },
  { Code: "US", Name: "United States" },
  { Code: "UM", Name: "United States Minor Outlying Islands" },
  { Code: "UY", Name: "Uruguay" },
  { Code: "UZ", Name: "Uzbekistan" },
  { Code: "VU", Name: "Vanuatu" },
  { Code: "VE", Name: "Venezuela, Bolivarian Republic of" },
  { Code: "VN", Name: "Viet Nam" },
  { Code: "VG", Name: "Virgin Islands, British" },
  { Code: "VI", Name: "Virgin Islands, U.S." },
  { Code: "WF", Name: "Wallis and Futuna" },
  { Code: "EH", Name: "Western Sahara" },
  { Code: "YE", Name: "Yemen" },
  { Code: "ZM", Name: "Zambia" },
  { Code: "ZW", Name: "Zimbabwe" },
];

export const rangeOfNumbers = (
  start: number,
  end: number,
  step = 1
): number[] => {
  start = Number(start);
  end = Number(end);
  if (!start) {
    return [];
  } else if (!end) {
    return [start];
  }
  const diff = start < end ? end - start : start - end;
  const smallerNum = start > end ? end : start;
  const len = Math.floor(diff / step) + 1;
  return Array(len)
    .fill(undefined)
    .map((_, idx) => smallerNum + idx * step);
};

export const CALENDAR_YEAR_LIST = rangeOfNumbers(1970, 2050).map((year) => ({
  value: year,
  label: String(year),
}));

export const MONTHS_ARRAY = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "Novermber",
  "December",
];

export const CALENDAR_MONTH_LIST = MONTHS_ARRAY.map((month) => ({
  value: month,
  label: month,
}));

export const FULLCALENDAR_TIME_NAME_MAPPING = {
  month: "dayGridMonth",
  year: "multiMonthYear",
};
