export const COUNTRY_CALENDAR_MAP = {
  Afghanistan: "enaf#holiday@group.v.calendar.google.com",
  Albania: "enal#holiday@group.v.calendar.google.com",
  Algeria: "endz#holiday@group.v.calendar.google.com",
  "American Samoa": "enas#holiday@group.v.calendar.google.com",
  Andorra: "enad#holiday@group.v.calendar.google.com",
  Angola: "enao#holiday@group.v.calendar.google.com",
  Anguilla: "enai#holiday@group.v.calendar.google.com",
  "Antigua and Barbuda": "enag#holiday@group.v.calendar.google.com",
  Argentina: "enar#holiday@group.v.calendar.google.com",
  Armenia: "enam#holiday@group.v.calendar.google.com",
  Aruba: "enaw#holiday@group.v.calendar.google.com",
  Australia: "enaustralian#holiday@group.v.calendar.google.com",
  Austria: "enaustrian#holiday@group.v.calendar.google.com",
  Azerbaijan: "enaz#holiday@group.v.calendar.google.com",
  Bahamas: "enbs#holiday@group.v.calendar.google.com",
  Bahrain: "enbh#holiday@group.v.calendar.google.com",
  Bangladesh: "enbd#holiday@group.v.calendar.google.com",
  Barbados: "enbb#holiday@group.v.calendar.google.com",
  Belarus: "enby#holiday@group.v.calendar.google.com",
  Belgium: "enbe#holiday@group.v.calendar.google.com",
  Belize: "enbz#holiday@group.v.calendar.google.com",
  Benin: "enbj#holiday@group.v.calendar.google.com",
  Bermuda: "enbm#holiday@group.v.calendar.google.com",
  Bhutan: "enbt#holiday@group.v.calendar.google.com",
  Bolivia: "enbo#holiday@group.v.calendar.google.com",
  "Bosnia and Herzegovina": "enba#holiday@group.v.calendar.google.com",
  Botswana: "enbw#holiday@group.v.calendar.google.com",
  Brazil: "enbrazilian#holiday@group.v.calendar.google.com",
  "British Virgin Islands": "envg#holiday@group.v.calendar.google.com",
  "Brunei Darussalam": "enbn#holiday@group.v.calendar.google.com",
  Bulgaria: "enbulgarian#holiday@group.v.calendar.google.com",
  "Burkina Faso": "enbf#holiday@group.v.calendar.google.com",
  Burundi: "enbi#holiday@group.v.calendar.google.com",
  Cambodia: "enkh#holiday@group.v.calendar.google.com",
  Cameroon: "encm#holiday@group.v.calendar.google.com",
  Canada: "encanadian#holiday@group.v.calendar.google.com",
  "Cape Verde": "encv#holiday@group.v.calendar.google.com",
  "Cayman Islands": "enky#holiday@group.v.calendar.google.com",
  "Central African Republic": "encf#holiday@group.v.calendar.google.com",
  Chad: "entd#holiday@group.v.calendar.google.com",
  Chile: "encl#holiday@group.v.calendar.google.com",
  China: "enchina#holiday@group.v.calendar.google.com",
  Colombia: "enco#holiday@group.v.calendar.google.com",
  "com,oros": "enkm#holiday@group.v.calendar.google.com",
  Congo: "encg#holiday@group.v.calendar.google.com",
  "Cook Islands": "enck#holiday@group.v.calendar.google.com",
  "Costa Rica": "encr#holiday@group.v.calendar.google.com",
  "Côte d'Ivoire": "enci#holiday@group.v.calendar.google.com",
  Croatia: "encroatian#holiday@group.v.calendar.google.com",
  Cuba: "encu#holiday@group.v.calendar.google.com",
  Curaçao: "encw#holiday@group.v.calendar.google.com",
  Cyprus: "ency#holiday@group.v.calendar.google.com",
  Czechia: "enczech#holiday@group.v.calendar.google.com",
  "Democratic People's Republic of Korea":
    "enkp#holiday@group.v.calendar.google.com",
  Denmark: "endanish#holiday@group.v.calendar.google.com",
  Djibouti: "endj#holiday@group.v.calendar.google.com",
  Dominica: "endm#holiday@group.v.calendar.google.com",
  "Dominican Republic": "endo#holiday@group.v.calendar.google.com",
  Ecuador: "enec#holiday@group.v.calendar.google.com",
  Egypt: "eneg#holiday@group.v.calendar.google.com",
  "El Salvador": "ensv#holiday@group.v.calendar.google.com",
  "Equatorial Guinea": "engq#holiday@group.v.calendar.google.com",
  Eritrea: "ener#holiday@group.v.calendar.google.com",
  Estonia: "enee#holiday@group.v.calendar.google.com",
  Ethiopia: "enet#holiday@group.v.calendar.google.com",
  "Falkland Islands (Malvinas)": "enfk#holiday@group.v.calendar.google.com",
  "Faroe Islands": "enfo#holiday@group.v.calendar.google.com",
  "Federated States of Micronesia": "enfm#holiday@group.v.calendar.google.com",
  Fiji: "enfj#holiday@group.v.calendar.google.com",
  Finland: "enfinnish#holiday@group.v.calendar.google.com",
  France: "enfrench#holiday@group.v.calendar.google.com",
  "French Guiana": "engf#holiday@group.v.calendar.google.com",
  "French Polynesia": "enpf#holiday@group.v.calendar.google.com",
  Gabon: "enga#holiday@group.v.calendar.google.com",
  Gambia: "engm#holiday@group.v.calendar.google.com",
  Georgia: "enge#holiday@group.v.calendar.google.com",
  Germany: "engerman#holiday@group.v.calendar.google.com",
  Ghana: "engh#holiday@group.v.calendar.google.com",
  Gibraltar: "engi#holiday@group.v.calendar.google.com",
  Greece: "engreek#holiday@group.v.calendar.google.com",
  Greenland: "engl#holiday@group.v.calendar.google.com",
  Grenada: "engd#holiday@group.v.calendar.google.com",
  Guam: "engu#holiday@group.v.calendar.google.com",
  Guatemala: "engt#holiday@group.v.calendar.google.com",
  Guernsey: "engg#holiday@group.v.calendar.google.com",
  Guinea: "engn#holiday@group.v.calendar.google.com",
  "Guinea-Bissau": "engw#holiday@group.v.calendar.google.com",
  Guyana: "engy#holiday@group.v.calendar.google.com",
  Haiti: "enht#holiday@group.v.calendar.google.com",
  "Holy See (Vatican City State)": "enva#holiday@group.v.calendar.google.com",
  Honduras: "enhn#holiday@group.v.calendar.google.com",
  "Hong Kong": "enhong_kong#holiday@group.v.calendar.google.com",
  Hungary: "enhungarian#holiday@group.v.calendar.google.com",
  Iceland: "enis#holiday@group.v.calendar.google.com",
  India: "enindian#holiday@group.v.calendar.google.com",
  Indonesia: "enindonesian#holiday@group.v.calendar.google.com",
  Iraq: "eniq#holiday@group.v.calendar.google.com",
  Ireland: "enirish#holiday@group.v.calendar.google.com",
  "Islamic Republic of Iran": "enir#holiday@group.v.calendar.google.com",
  "Isle of Man": "enim#holiday@group.v.calendar.google.com",
  Israel: "enjewish#holiday@group.v.calendar.google.com",
  Italy: "enitalian#holiday@group.v.calendar.google.com",
  Jamaica: "enjm#holiday@group.v.calendar.google.com",
  Japan: "enjapanese#holiday@group.v.calendar.google.com",
  Jersey: "enje#holiday@group.v.calendar.google.com",
  Jordan: "enjo#holiday@group.v.calendar.google.com",
  Kazakhstan: "enkz#holiday@group.v.calendar.google.com",
  Kenya: "enke#holiday@group.v.calendar.google.com",
  Kiribati: "enki#holiday@group.v.calendar.google.com",
  Kuwait: "enkw#holiday@group.v.calendar.google.com",
  Kyrgyzstan: "enkg#holiday@group.v.calendar.google.com",
  "Lao People's Democratic Republic":
    "enla#holiday@group.v.calendar.google.com",
  Latvia: "enlatvian#holiday@group.v.calendar.google.com",
  Lebanon: "enlb#holiday@group.v.calendar.google.com",
  Lesotho: "enls#holiday@group.v.calendar.google.com",
  Liberia: "enlr#holiday@group.v.calendar.google.com",
  Libya: "enly#holiday@group.v.calendar.google.com",
  Liechtenstein: "enli#holiday@group.v.calendar.google.com",
  Lithuania: "enlithuanian#holiday@group.v.calendar.google.com",
  Luxembourg: "enlu#holiday@group.v.calendar.google.com",
  Macao: "enmo#holiday@group.v.calendar.google.com",
  Madagascar: "enmg#holiday@group.v.calendar.google.com",
  Malawi: "enmw#holiday@group.v.calendar.google.com",
  Malaysia: "enmalaysia#holiday@group.v.calendar.google.com",
  Maldives: "enmv#holiday@group.v.calendar.google.com",
  Mali: "enml#holiday@group.v.calendar.google.com",
  Malta: "enmt#holiday@group.v.calendar.google.com",
  "Marshall Islands": "enmh#holiday@group.v.calendar.google.com",
  Martinique: "enmq#holiday@group.v.calendar.google.com",
  Mauritania: "enmr#holiday@group.v.calendar.google.com",
  Mauritius: "enmu#holiday@group.v.calendar.google.com",
  Mayotte: "enyt#holiday@group.v.calendar.google.com",
  Mexico: "enmexican#holiday@group.v.calendar.google.com",
  Moldova: "enmd#holiday@group.v.calendar.google.com",
  Monaco: "enmc#holiday@group.v.calendar.google.com",
  Mongolia: "enmn#holiday@group.v.calendar.google.com",
  Montenegro: "enme#holiday@group.v.calendar.google.com",
  Montserrat: "enms#holiday@group.v.calendar.google.com",
  Morocco: "enma#holiday@group.v.calendar.google.com",
  Mozambique: "enmz#holiday@group.v.calendar.google.com",
  Myanmar: "enmm#holiday@group.v.calendar.google.com",
  Namibia: "enna#holiday@group.v.calendar.google.com",
  Nauru: "ennr#holiday@group.v.calendar.google.com",
  Nepal: "ennp#holiday@group.v.calendar.google.com",
  Netherlands: "endutch#holiday@group.v.calendar.google.com",
  "New Caledonia": "ennc#holiday@group.v.calendar.google.com",
  "New Zealand": "ennew_zealand#holiday@group.v.calendar.google.com",
  Nicaragua: "enni#holiday@group.v.calendar.google.com",
  Niger: "enne#holiday@group.v.calendar.google.com",
  Nigeria: "enng#holiday@group.v.calendar.google.com",
  "Northern Mariana Islands": "enmp#holiday@group.v.calendar.google.com",
  Norway: "ennorwegian#holiday@group.v.calendar.google.com",
  Oman: "enom#holiday@group.v.calendar.google.com",
  Pakistan: "enpk#holiday@group.v.calendar.google.com",
  Palau: "enpw#holiday@group.v.calendar.google.com",
  Panama: "enpa#holiday@group.v.calendar.google.com",
  "Papua New Guinea": "enpg#holiday@group.v.calendar.google.com",
  Paraguay: "enpy#holiday@group.v.calendar.google.com",
  Peru: "enpe#holiday@group.v.calendar.google.com",
  Philippines: "enphilippines#holiday@group.v.calendar.google.com",
  Poland: "enpolish#holiday@group.v.calendar.google.com",
  Portugal: "enportuguese#holiday@group.v.calendar.google.com",
  "Puerto Rico": "enpr#holiday@group.v.calendar.google.com",
  Qatar: "enqa#holiday@group.v.calendar.google.com",
  "Republic of Korea": "ensouth_korea#holiday@group.v.calendar.google.com",
  Réunion: "enre#holiday@group.v.calendar.google.com",
  Romania: "enromanian#holiday@group.v.calendar.google.com",
  "Russian Federation": "enrussian#holiday@group.v.calendar.google.com",
  Rwanda: "enrw#holiday@group.v.calendar.google.com",
  "Saint Barthélemy": "enbl#holiday@group.v.calendar.google.com",
  "Saint Helena": "ensh#holiday@group.v.calendar.google.com",
  "Saint Kitts and Nevis": "enkn#holiday@group.v.calendar.google.com",
  "Saint Lucia": "enlc#holiday@group.v.calendar.google.com",
  "Saint Martin (French part)": "enmf#holiday@group.v.calendar.google.com",
  "Saint Pierre and Miquelon": "enpm#holiday@group.v.calendar.google.com",
  "Saint Vincent and the Grenadines":
    "envc#holiday@group.v.calendar.google.com",
  Samoa: "enws#holiday@group.v.calendar.google.com",
  "San Marino": "ensm#holiday@group.v.calendar.google.com",
  "Sao Tome and Principe": "enst#holiday@group.v.calendar.google.com",
  "Saudi Arabia": "ensaudiarabian#holiday@group.v.calendar.google.com",
  Senegal: "ensn#holiday@group.v.calendar.google.com",
  Serbia: "enrs#holiday@group.v.calendar.google.com",
  Seychelles: "ensc#holiday@group.v.calendar.google.com",
  "Sierra Leone": "ensl#holiday@group.v.calendar.google.com",
  Singapore: "ensingapore#holiday@group.v.calendar.google.com",
  "Sint Maarten (Dutch part)": "ensx#holiday@group.v.calendar.google.com",
  Slovakia: "enslovak#holiday@group.v.calendar.google.com",
  Slovenia: "enslovenian#holiday@group.v.calendar.google.com",
  "Solomon Islands": "ensb#holiday@group.v.calendar.google.com",
  Somalia: "enso#holiday@group.v.calendar.google.com",
  "South Africa": "ensa#holiday@group.v.calendar.google.com",
  "South Sudan": "enss#holiday@group.v.calendar.google.com",
  Spain: "enspain#holiday@group.v.calendar.google.com",
  "Sri Lanka": "enlk#holiday@group.v.calendar.google.com",
  Sudan: "ensd#holiday@group.v.calendar.google.com",
  Suriname: "ensr#holiday@group.v.calendar.google.com",
  Swaziland: "ensz#holiday@group.v.calendar.google.com",
  Sweden: "enswedish#holiday@group.v.calendar.google.com",
  Switzerland: "ench#holiday@group.v.calendar.google.com",
  "Syrian Arab Republic": "ensy#holiday@group.v.calendar.google.com",
  Taiwan: "entaiwan#holiday@group.v.calendar.google.com",
  Tajikistan: "entj#holiday@group.v.calendar.google.com",
  Thailand: "enth#holiday@group.v.calendar.google.com",
  "The Democratic Republic of the Congo":
    "encd#holiday@group.v.calendar.google.com",
  "The Former Yugoslav Republic of Macedonia":
    "enmk#holiday@group.v.calendar.google.com",
  "Timor-Leste": "entl#holiday@group.v.calendar.google.com",
  Togo: "entg#holiday@group.v.calendar.google.com",
  Tonga: "ento#holiday@group.v.calendar.google.com",
  "Trinidad and Tobago": "entt#holiday@group.v.calendar.google.com",
  Tunisia: "entn#holiday@group.v.calendar.google.com",
  Turkey: "enturkish#holiday@group.v.calendar.google.com",
  Turkmenistan: "entm#holiday@group.v.calendar.google.com",
  "Turks and Caicos Islands": "entc#holiday@group.v.calendar.google.com",
  Tuvalu: "entv#holiday@group.v.calendar.google.com",
  "U.S. Virgin Islands": "envi#holiday@group.v.calendar.google.com",
  Uganda: "enug#holiday@group.v.calendar.google.com",
  Ukraine: "enukrainian#holiday@group.v.calendar.google.com",
  "United Arab Emirates": "enae#holiday@group.v.calendar.google.com",
  "United Kingdom": "enuk#holiday@group.v.calendar.google.com",
  "United Republic of Tanzania": "entz#holiday@group.v.calendar.google.com",
  "United States": "enusa#holiday@group.v.calendar.google.com",
  Uruguay: "enuy#holiday@group.v.calendar.google.com",
  Uzbekistan: "enuz#holiday@group.v.calendar.google.com",
  Vanuatu: "envu#holiday@group.v.calendar.google.com",
  Venezuela: "enve#holiday@group.v.calendar.google.com",
  Vietnam: "envietnamese#holiday@group.v.calendar.google.com",
  "Wallis and Futuna": "enwf#holiday@group.v.calendar.google.com",
  Yemen: "enye#holiday@group.v.calendar.google.com",
  Zambia: "enzm#holiday@group.v.calendar.google.com",
  Zimbabwe: "enzw#holiday@group.v.calendar.google.com",
};

export interface CountryListItem {
  Code: string;
  Name: string;
}

export const COUNTRY_LIST: CountryListItem[] = [
  { Code: "AF", Name: "Afghanistan" },
  { Code: "AX", Name: "\u00c5land Islands" },
  { Code: "AL", Name: "Albania" },
  { Code: "DZ", Name: "Algeria" },
  { Code: "AS", Name: "American Samoa" },
  { Code: "AD", Name: "Andorra" },
  { Code: "AO", Name: "Angola" },
  { Code: "AI", Name: "Anguilla" },
  { Code: "AQ", Name: "Antarctica" },
  { Code: "AG", Name: "Antigua and Barbuda" },
  { Code: "AR", Name: "Argentina" },
  { Code: "AM", Name: "Armenia" },
  { Code: "AW", Name: "Aruba" },
  { Code: "AU", Name: "Australia" },
  { Code: "AT", Name: "Austria" },
  { Code: "AZ", Name: "Azerbaijan" },
  { Code: "BS", Name: "Bahamas" },
  { Code: "BH", Name: "Bahrain" },
  { Code: "BD", Name: "Bangladesh" },
  { Code: "BB", Name: "Barbados" },
  { Code: "BY", Name: "Belarus" },
  { Code: "BE", Name: "Belgium" },
  { Code: "BZ", Name: "Belize" },
  { Code: "BJ", Name: "Benin" },
  { Code: "BM", Name: "Bermuda" },
  { Code: "BT", Name: "Bhutan" },
  { Code: "BO", Name: "Bolivia, Plurinational State of" },
  { Code: "BQ", Name: "Bonaire, Sint Eustatius and Saba" },
  { Code: "BA", Name: "Bosnia and Herzegovina" },
  { Code: "BW", Name: "Botswana" },
  { Code: "BV", Name: "Bouvet Island" },
  { Code: "BR", Name: "Brazil" },
  { Code: "IO", Name: "British Indian Ocean Territory" },
  { Code: "BN", Name: "Brunei Darussalam" },
  { Code: "BG", Name: "Bulgaria" },
  { Code: "BF", Name: "Burkina Faso" },
  { Code: "BI", Name: "Burundi" },
  { Code: "KH", Name: "Cambodia" },
  { Code: "CM", Name: "Cameroon" },
  { Code: "CA", Name: "Canada" },
  { Code: "CV", Name: "Cape Verde" },
  { Code: "KY", Name: "Cayman Islands" },
  { Code: "CF", Name: "Central African Republic" },
  { Code: "TD", Name: "Chad" },
  { Code: "CL", Name: "Chile" },
  { Code: "CN", Name: "China" },
  { Code: "CX", Name: "Christmas Island" },
  { Code: "CC", Name: "Cocos (Keeling) Islands" },
  { Code: "CO", Name: "Colombia" },
  { Code: "KM", Name: "Comoros" },
  { Code: "CG", Name: "Congo" },
  { Code: "CD", Name: "Congo, the Democratic Republic of the" },
  { Code: "CK", Name: "Cook Islands" },
  { Code: "CR", Name: "Costa Rica" },
  { Code: "CI", Name: "C\u00f4te d'Ivoire" },
  { Code: "HR", Name: "Croatia" },
  { Code: "CU", Name: "Cuba" },
  { Code: "CW", Name: "Cura\u00e7ao" },
  { Code: "CY", Name: "Cyprus" },
  { Code: "CZ", Name: "Czech Republic" },
  { Code: "DK", Name: "Denmark" },
  { Code: "DJ", Name: "Djibouti" },
  { Code: "DM", Name: "Dominica" },
  { Code: "DO", Name: "Dominican Republic" },
  { Code: "EC", Name: "Ecuador" },
  { Code: "EG", Name: "Egypt" },
  { Code: "SV", Name: "El Salvador" },
  { Code: "GQ", Name: "Equatorial Guinea" },
  { Code: "ER", Name: "Eritrea" },
  { Code: "EE", Name: "Estonia" },
  { Code: "ET", Name: "Ethiopia" },
  { Code: "FK", Name: "Falkland Islands (Malvinas)" },
  { Code: "FO", Name: "Faroe Islands" },
  { Code: "FJ", Name: "Fiji" },
  { Code: "FI", Name: "Finland" },
  { Code: "FR", Name: "France" },
  { Code: "GF", Name: "French Guiana" },
  { Code: "PF", Name: "French Polynesia" },
  { Code: "TF", Name: "French Southern Territories" },
  { Code: "GA", Name: "Gabon" },
  { Code: "GM", Name: "Gambia" },
  { Code: "GE", Name: "Georgia" },
  { Code: "DE", Name: "Germany" },
  { Code: "GH", Name: "Ghana" },
  { Code: "GI", Name: "Gibraltar" },
  { Code: "GR", Name: "Greece" },
  { Code: "GL", Name: "Greenland" },
  { Code: "GD", Name: "Grenada" },
  { Code: "GP", Name: "Guadeloupe" },
  { Code: "GU", Name: "Guam" },
  { Code: "GT", Name: "Guatemala" },
  { Code: "GG", Name: "Guernsey" },
  { Code: "GN", Name: "Guinea" },
  { Code: "GW", Name: "Guinea-Bissau" },
  { Code: "GY", Name: "Guyana" },
  { Code: "HT", Name: "Haiti" },
  { Code: "HM", Name: "Heard Island and McDonald Islands" },
  { Code: "VA", Name: "Holy See (Vatican City State)" },
  { Code: "HN", Name: "Honduras" },
  { Code: "HK", Name: "Hong Kong" },
  { Code: "HU", Name: "Hungary" },
  { Code: "IS", Name: "Iceland" },
  { Code: "IN", Name: "India" },
  { Code: "ID", Name: "Indonesia" },
  { Code: "IR", Name: "Iran, Islamic Republic of" },
  { Code: "IQ", Name: "Iraq" },
  { Code: "IE", Name: "Ireland" },
  { Code: "IM", Name: "Isle of Man" },
  { Code: "IL", Name: "Israel" },
  { Code: "IT", Name: "Italy" },
  { Code: "JM", Name: "Jamaica" },
  { Code: "JP", Name: "Japan" },
  { Code: "JE", Name: "Jersey" },
  { Code: "JO", Name: "Jordan" },
  { Code: "KZ", Name: "Kazakhstan" },
  { Code: "KE", Name: "Kenya" },
  { Code: "KI", Name: "Kiribati" },
  { Code: "KP", Name: "Korea, Democratic People's Republic of" },
  { Code: "KR", Name: "Korea, Republic of" },
  { Code: "KW", Name: "Kuwait" },
  { Code: "KG", Name: "Kyrgyzstan" },
  { Code: "LA", Name: "Lao People's Democratic Republic" },
  { Code: "LV", Name: "Latvia" },
  { Code: "LB", Name: "Lebanon" },
  { Code: "LS", Name: "Lesotho" },
  { Code: "LR", Name: "Liberia" },
  { Code: "LY", Name: "Libya" },
  { Code: "LI", Name: "Liechtenstein" },
  { Code: "LT", Name: "Lithuania" },
  { Code: "LU", Name: "Luxembourg" },
  { Code: "MO", Name: "Macao" },
  { Code: "MK", Name: "Macedonia, the Former Yugoslav Republic of" },
  { Code: "MG", Name: "Madagascar" },
  { Code: "MW", Name: "Malawi" },
  { Code: "MY", Name: "Malaysia" },
  { Code: "MV", Name: "Maldives" },
  { Code: "ML", Name: "Mali" },
  { Code: "MT", Name: "Malta" },
  { Code: "MH", Name: "Marshall Islands" },
  { Code: "MQ", Name: "Martinique" },
  { Code: "MR", Name: "Mauritania" },
  { Code: "MU", Name: "Mauritius" },
  { Code: "YT", Name: "Mayotte" },
  { Code: "MX", Name: "Mexico" },
  { Code: "FM", Name: "Micronesia, Federated States of" },
  { Code: "MD", Name: "Moldova, Republic of" },
  { Code: "MC", Name: "Monaco" },
  { Code: "MN", Name: "Mongolia" },
  { Code: "ME", Name: "Montenegro" },
  { Code: "MS", Name: "Montserrat" },
  { Code: "MA", Name: "Morocco" },
  { Code: "MZ", Name: "Mozambique" },
  { Code: "MM", Name: "Myanmar" },
  { Code: "NA", Name: "Namibia" },
  { Code: "NR", Name: "Nauru" },
  { Code: "NP", Name: "Nepal" },
  { Code: "NL", Name: "Netherlands" },
  { Code: "NC", Name: "New Caledonia" },
  { Code: "NZ", Name: "New Zealand" },
  { Code: "NI", Name: "Nicaragua" },
  { Code: "NE", Name: "Niger" },
  { Code: "NG", Name: "Nigeria" },
  { Code: "NU", Name: "Niue" },
  { Code: "NF", Name: "Norfolk Island" },
  { Code: "MP", Name: "Northern Mariana Islands" },
  { Code: "NO", Name: "Norway" },
  { Code: "OM", Name: "Oman" },
  { Code: "PK", Name: "Pakistan" },
  { Code: "PW", Name: "Palau" },
  { Code: "PS", Name: "Palestine, State of" },
  { Code: "PA", Name: "Panama" },
  { Code: "PG", Name: "Papua New Guinea" },
  { Code: "PY", Name: "Paraguay" },
  { Code: "PE", Name: "Peru" },
  { Code: "PH", Name: "Philippines" },
  { Code: "PN", Name: "Pitcairn" },
  { Code: "PL", Name: "Poland" },
  { Code: "PT", Name: "Portugal" },
  { Code: "PR", Name: "Puerto Rico" },
  { Code: "QA", Name: "Qatar" },
  { Code: "RE", Name: "R\u00e9union" },
  { Code: "RO", Name: "Romania" },
  { Code: "RU", Name: "Russian Federation" },
  { Code: "RW", Name: "Rwanda" },
  { Code: "BL", Name: "Saint Barth\u00e9lemy" },
  { Code: "SH", Name: "Saint Helena, Ascension and Tristan da Cunha" },
  { Code: "KN", Name: "Saint Kitts and Nevis" },
  { Code: "LC", Name: "Saint Lucia" },
  { Code: "MF", Name: "Saint Martin (French part)" },
  { Code: "PM", Name: "Saint Pierre and Miquelon" },
  { Code: "VC", Name: "Saint Vincent and the Grenadines" },
  { Code: "WS", Name: "Samoa" },
  { Code: "SM", Name: "San Marino" },
  { Code: "ST", Name: "Sao Tome and Principe" },
  { Code: "SA", Name: "Saudi Arabia" },
  { Code: "SN", Name: "Senegal" },
  { Code: "RS", Name: "Serbia" },
  { Code: "SC", Name: "Seychelles" },
  { Code: "SL", Name: "Sierra Leone" },
  { Code: "SG", Name: "Singapore" },
  { Code: "SX", Name: "Sint Maarten (Dutch part)" },
  { Code: "SK", Name: "Slovakia" },
  { Code: "SI", Name: "Slovenia" },
  { Code: "SB", Name: "Solomon Islands" },
  { Code: "SO", Name: "Somalia" },
  { Code: "ZA", Name: "South Africa" },
  { Code: "GS", Name: "South Georgia and the South Sandwich Islands" },
  { Code: "SS", Name: "South Sudan" },
  { Code: "ES", Name: "Spain" },
  { Code: "LK", Name: "Sri Lanka" },
  { Code: "SD", Name: "Sudan" },
  { Code: "SR", Name: "Suriname" },
  { Code: "SJ", Name: "Svalbard and Jan Mayen" },
  { Code: "SZ", Name: "Swaziland" },
  { Code: "SE", Name: "Sweden" },
  { Code: "CH", Name: "Switzerland" },
  { Code: "SY", Name: "Syrian Arab Republic" },
  { Code: "TW", Name: "Taiwan, Province of China" },
  { Code: "TJ", Name: "Tajikistan" },
  { Code: "TZ", Name: "Tanzania, United Republic of" },
  { Code: "TH", Name: "Thailand" },
  { Code: "TL", Name: "Timor-Leste" },
  { Code: "TG", Name: "Togo" },
  { Code: "TK", Name: "Tokelau" },
  { Code: "TO", Name: "Tonga" },
  { Code: "TT", Name: "Trinidad and Tobago" },
  { Code: "TN", Name: "Tunisia" },
  { Code: "TR", Name: "Turkey" },
  { Code: "TM", Name: "Turkmenistan" },
  { Code: "TC", Name: "Turks and Caicos Islands" },
  { Code: "TV", Name: "Tuvalu" },
  { Code: "UG", Name: "Uganda" },
  { Code: "UA", Name: "Ukraine" },
  { Code: "AE", Name: "United Arab Emirates" },
  { Code: "GB", Name: "United Kingdom" },
  { Code: "US", Name: "United States" },
  { Code: "UM", Name: "United States Minor Outlying Islands" },
  { Code: "UY", Name: "Uruguay" },
  { Code: "UZ", Name: "Uzbekistan" },
  { Code: "VU", Name: "Vanuatu" },
  { Code: "VE", Name: "Venezuela, Bolivarian Republic of" },
  { Code: "VN", Name: "Viet Nam" },
  { Code: "VG", Name: "Virgin Islands, British" },
  { Code: "VI", Name: "Virgin Islands, U.S." },
  { Code: "WF", Name: "Wallis and Futuna" },
  { Code: "EH", Name: "Western Sahara" },
  { Code: "YE", Name: "Yemen" },
  { Code: "ZM", Name: "Zambia" },
  { Code: "ZW", Name: "Zimbabwe" },
];

const rangeOfNumbers = (start = 0, end = 2, step = 1) => {
  const len = Math.floor((end - start) / step) + 1;
  return Array(len)
    .fill(undefined)
    .map((_, idx) => start + idx * step);
};

export const CALENDAR_YEAR_LIST = rangeOfNumbers(1970, 2050).map((year) => ({
  value: year,
  label: String(year),
}));

export const CALENDAR_MONTH_LIST = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "Novermber",
  "December",
].map((month) => ({ value: month, label: month }));
